version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    assignees:
      - vinayakkulkarni
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Cargo (Rust)
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    assignees:
      - vinayakkulkarni
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Bun - Root workspace
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    assignees:
      - vinayakkulkarni
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Bun - Nuxt client app
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/apps/client"
    schedule:
      interval: daily
      time: "00:00"
    assignees:
      - vinayakkulkarni
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Bun - Documentation
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/docs"
    schedule:
      interval: daily
      time: "00:00"
    assignees:
      - vinayakkulkarni
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
