[package]
name = "tileserver-rs"
version = "0.1.0"
edition = "2021"
authors = ["Vinayak Kulkarni <inbox.vinayak@gmail.com>"]
description = "Tileserver for serving vector tiles (& raster tiles) from mbtiles"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/vinayakkulkarni/tileserver-rs"
keywords = ["pmtiles", "mbtiles", "gis", "vector-tiles", "tileserver"]

[dependencies]
actix-web = "4"
pmtiles = "0.2.1"
serde = { version = "1.0.152", features = ["derive"] }
